### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by MatthewFrench** [jpakkane/monocoque#1]
When running the example, the command "meson .." starts but eventually outputs the error "NameError: name 'ssl' is not defined" when it tries to "Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/sdl2/2.0.3/2/get_zip".

Operating system: Mac OS 10.11

Full terminal log: 

Last login: Thu Nov 19 07:51:05 on ttys000
Matthews-MacBook-Pro:~ Matt$ cd /Users/Matt/Downloads/monocoque-master 
Matthews-MacBook-Pro:monocoque-master Matt$ cd build
Matthews-MacBook-Pro:build Matt$ meson ..
Warning: ssl not available, traffic not authenticated.
The Meson build system
Version: 0.27.0-research
Source dir: /Users/Matt/Downloads/monocoque-master
Build dir: /Users/Matt/Downloads/monocoque-master/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: monocoque demo
Native cpp compiler: c++ (clang 7.0.0)
Dowloading sdl2 from https://libsdl.org/release/SDL2-2.0.3.zip
Download size: 4764799
Downloading: ..........
Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/sdl2/2.0.3/2/get_zip
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 208, in run
    app.generate()
  File "/usr/local/bin/meson", line 160, in generate
    intr.run()
  File "/usr/local/share/meson/interpreter.py", line 1029, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/share/meson/interpreter.py", line 1051, in evaluate_codeblock
    raise e
  File "/usr/local/share/meson/interpreter.py", line 1045, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/share/meson/interpreter.py", line 1163, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/share/meson/interpreter.py", line 1963, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/share/meson/interpreter.py", line 1161, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/share/meson/interpreter.py", line 1944, in function_call
    return self.funcs[func_name](node, self.flatten%28posargs%29, kwargs)
  File "/usr/local/share/meson/interpreter.py", line 69, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/local/share/meson/interpreter.py", line 1282, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/local/share/meson/interpreter.py", line 1296, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/local/share/meson/wrap.py", line 66, in resolve
    self.download(p, packagename)
  File "/usr/local/share/meson/wrap.py", line 143, in download
    pdata = self.get_data(purl)
  File "/usr/local/share/meson/wrap.py", line 97, in get_data
    resp = urllib.request.urlopen(url, context=build_ssl_context())
  File "/usr/local/share/meson/wraptool.py", line 98, in build_ssl_context
    ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
NameError: name 'ssl' is not defined
Matthews-MacBook-Pro:build Matt$

**Comment by jpakkane** [comment]
Fixed. Please update your Meson checkout and try again.
